name: my_gallery_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  fluttertoast: ^8.2.1
  file_picker: ^5.2.7
  shared_preferences: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Segoe UI
      fonts:
        - asset: assets/fonts/segoe_ui.ttf
          weight: 300
        - asset: assets/fonts/segoe_ui_bold.ttf
          weight: 700


